version: "3.8"

services:
  social_network_platform:
    restart: always 
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: social_network_platform
    env_file: .env
    ports:
    - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT} 
    networks:
    - social_network_net
    depends_on: 
    - postgresql
    - mongodb
    - redis
    - rabbitmq

  postgresql:
    restart: always
    container_name: postgresql
    image: postgres
    env_file: .env
    environment: 
    - ${POSTGRES_USER}
    - ${POSTGRES_PASSWORD}
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
    - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
    networks:
    - social_network_net

  mongodb:
    restart: always
    image: mongo
    container_name: mongodb
    ports:
    - ${MONGO_PORT}:${MONGO_PORT}
    env_file: .env
    environment:
    - ${MONGO_INITDB_ROOT_USERNAME}
    - ${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
    - ${MONGO_VOLUME_PATH}:/var/lib/docker/mongodb/_data
    networks:
    - social_network_net

  redis:
    restart: always
    image: redis
    container_name: redis
    env_file: .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - social_network_net

  rabbitmq:
    restart: always
    image: rabbitmq
    container_name: rabbitmq
    ports:
    - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    env_file: .env
    environment:
    - ${RABBITMQ_DEFAULT_USER}
    - ${RABBITMQ_DEFAULT_PASS}
    networks:
      - social_network_net

networks:
  social_network_net: