env: "local" # local, dev, prod 

service: 
  name: "SocialNetwork-NorthVoid"
  version: "0.1.3"

http_server:
  idle_timeout: 60s
  write_timeout: 30s
  read_timeout: 30s
  max_header_mb: 20

internal_services:
  sso_service:
    name: sso_service
    version: "0.1.3"
    http_port: "8081"
    # grpc_port:
